services:
  - type: web
    name: chat-backend
    env: node
    buildCommand: npm install
    startCommand: node index.js
    envVars:
      - key: MONGO_URL
        value: your-mongodb-uri
      - key: JWT_SECRET
        value: your-secret
